name: Deploy

on:
  schedule:
    - cron: "1 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Send POST Request
        env:
          HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: |
          curl -X POST $HOOK

